### ISSUE TITLE
get_token

### ISSUE THREAD

**Issue by louisedaixum** [rweyant/spotifyr#1]
client_tokens <- get_tokens()
 Error in system(paste(curl_cmd, " -H "Authorization: Basic ", base64(paste(client_id, : 'curl' not found can you help me again?

I have the package RCurl and httr

**Comment by rweyant** [comment]
OK, so I made a fix that is not really ideal, but should get you running.  I had a successfuly Windows 7 test this morning, and will do a 8 test later.  

You'll need to download (cURL)[http://curl.haxx.se/download.html] and **add it's location to your PATH environment variable in Windows**.  I was having an issue with RCurl and httr for some of the authentication calls, and so just used cURL, but this is not a sustainable long term solution.  I'm going to leave this issue open until I fix that actual underlying issue, but you should be good to go once you install cURL for Windows.  Also, the user authentication workflow depends on Firefox, Chrome and IE aren't supported yet.

**Comment by rweyant** [comment]
OK -- this authentication happens within R, using `httr`, without the need to download any extra software.  I've done some testing with Windows, and it looks good.  You do still need Firefox to handle the full user authentication flow, but you don't need to do anything extra other than have it installed.  I'll be adding Chrome and IE support soon, but those are not yet supported.  Let me know if you have any other problems.
