### ISSUE TITLE
get_tokens() method not working

### ISSUE THREAD

**Issue by quicksell-louis** [rweyant/spotifyr#5]
So when I try to run the following code:
`client_tokens <- get_tokens()`

I get the following error:
```
Error in content(response)$error$status : 
  $ operator is invalid for atomic vectors
```
It looks an atomic vector is being referenced when the get_response_content() method is being called on the POST response.  

So far I have only downloaded and installed the package and set the global vars using the following code:
`set_credentials(client_id="[my_id_here]",client_secret="[my_secret_here]",client_redirect_uri = "http://localhost:1410/")`

Any ideas?

**Comment by rweyant** [comment]
Yep! need to update `set_credentials` -- older version had it set these to the global R environment, but need to actually save it to the system environment.  Give me a sec to see if I can get a fix for you really quick

**Comment by rweyant** [comment]
try what you were doing with #6 -- and also know I dropped the `client_redirect_uri` parameter for this function, so e.g. `set_credentials(client_id="[my_id_here]",client_secret="[my_secret_here]")`
Also, if you don't want to have to do this, you can add these variables to your ~/.Renviron file:
`SPOTIFY_CLIENT={your_client_id}`
`SPOTIFY_SECRET={your_secret}`

your system environment variables, like in your ~/.bash_profile or ~/.bashrc or something like that

Let me know if this works and we can close this

**Comment by sergiospagnuolo** [comment]
Hey, @rweyant, sorry to jump in, but it still doesn't work. I also get the `$ operator is invalid for atomic vectors` for some reason. I also tried [Rspotify](https://github.com/guilhermesad/rspotify), but it gives me the same error.

Do you think the Spotify API is blocking this?

**Comment by rweyant** [comment]
No, I believe this is an R error. 

Can you do/confirm a couple things for me?
* Can you reinstall from master?
* Confirm that you have SPOTIFY_CLIENT and SPOTIFY_SECRET defined in your ~/.Renviron before you start your R session or use the new `set_credentials` with your client and secret?
* Send me the commands you are trying to run along with the output of `devtools::session_info()`?

Thanks

**Comment by sergiospagnuolo** [comment]
It worked, thank you. I was running an older version.
